---
title: "Distribution Reporting Summary"
output: html_document
---



```{r, echo=FALSE, message=FALSE}
source("password.R") ## loads a variable called password
library(RCurl)
library(stringr)
upass = str_c("mcnepal:", password)
dataCSVDonor = getURI("http://ona.io/api/v1/data/65052.csv", userpwd=upass, httpauth = 1L)
donors = read.csv(textConnection(dataCSVDonor), na.strings="n/a")
dataCSVDistributions = getURI("http://ona.io/api/v1/data/65043.csv", userpwd=upass, httpauth = 1L)
distributions = read.csv(textConnection(dataCSVDistributions), na.strings="n/a")
previous_distributions = read.csv("before_july_9.csv")
VDC_List = read.csv("vdc_code_list.csv")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

library(dplyr)

donors_NFI = filter(donors, distribution_information.kits_or_cash == 1)

donors_cash = filter(donors, distribution_information.kits_or_cash == 2)

donors_summary_NFI = donors_NFI %>% 
  group_by(distribution_information.vdc_name)%>%
  summarize(PlannedNFI = sum(distribution_information.number_of_kits))%>%
  arrange(distribution_information.vdc_name)

donors_summary_cash = donors_cash %>% 
  group_by(distribution_information.vdc_name)%>%
  summarize(PlannedCash = sum(distribution_information.cash_recipients))%>%
  arrange(distribution_information.vdc_name)

donors_summary = merge(donors_summary_NFI, donors_summary_cash, by.x = "distribution_information.vdc_name", by.y = "distribution_information.vdc_name", all = TRUE)

distributions_NFI = filter(distributions, distribution_information.kits_or_cash == 1)

distributions_cash = filter(distributions, distribution_information.kits_or_cash == 2)

distributions_summary_NFI = distributions_NFI %>% 
  group_by(distribution_information.vdc_name)%>%
  summarize(DistributedNFI = sum(review.total_distribution))%>%
  arrange(distribution_information.vdc_name)

distributions_summary_cash = distributions_cash %>% 
  group_by( distribution_information.vdc_name)%>%
  summarize(DistributedCash = sum(review.total_distribution))%>%
  arrange(distribution_information.vdc_name)

distribution_summary = merge(distributions_summary_NFI, distributions_summary_cash, by.x = "distribution_information.vdc_name", by.y = "distribution_information.vdc_name", all = TRUE)

distribution_summary = merge(donors_summary, distribution_summary, by.x = "distribution_information.vdc_name", by.y = "distribution_information.vdc_name", all = TRUE)

distribution_summary = merge(distribution_summary, previous_distributions, by.x = "distribution_information.vdc_name", by.y = "VDC", all=TRUE)

distribution_summary [is.na(distribution_summary)] = 0

distribution_summary$DistributedNFI = (distribution_summary$DistributedNFI + distribution_summary$Kits)
distribution_summary$DistributedCash = (distribution_summary$DistributedCash + distribution_summary$Cash)
distribution_summary$PlannedNFI = (distribution_summary$PlannedNFI + distribution_summary$Kits)
distribution_summary$PlannedCash = (distribution_summary$PlannedCash + distribution_summary$Cash)

distribution_summary = merge(distribution_summary, VDC_List, by.x = "distribution_information.vdc_name", by.y = "VDC",all.x =TRUE)

distribution_summary = distribution_summary [,c("District.y","distribution_information.vdc_name","Donor.y","PlannedNFI","DistributedNFI","PlannedCash","DistributedCash")] %>% arrange(District.y)

distribution_summary[,c(1,2)] <- sapply(distribution_summary[,c(1,2)],as.character)

write.csv(distribution_summary, file = "distribution_summary.csv", sep = ",", col.names = TRUE)

distribution_summary = rbind(distribution_summary, c ("Total","","",sum(distribution_summary$PlannedNFI),sum(distribution_summary$DistributedNFI),sum(distribution_summary$PlannedCash),sum(distribution_summary$DistributedCash)))
```

###Distribution Summary
```{r, echo=FALSE, message=FALSE}
knitr::kable(distribution_summary, col.names = c ("District","VDC","Donor","NFRI Allocated","NFRI Distributed","Cash Allocated","Cash Distributed"))
```

**Distributed** column is drawn from the [Distribution Reporting Form](https://beta.ona.io/mcnepal/4384/65043), from `r nrow(distributions)` records.
**Allocated** column is drawn from the [Distribution Donor Form](https://beta.ona.io/mcnepal/4384/65052), from `r nrow(donors)` records.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
distributions_dfid_NFI = filter(donors, donors$distribution_information.distribution_donor == "dfid") %>%
  group_by(distribution_information.vdc_name) %>% 
  summarize(PlannedNFI_DFID = sum(distribution_information.number_of_kits, na.rm = TRUE))

distributions_dfid_cash = filter(donors, donors$distribution_information.distribution_donor == "dfid") %>%
  group_by(distribution_information.vdc_name) %>% 
  summarize(PlannedCash_DFID = sum(distribution_information.cash_recipients, na.rm = TRUE))

distributions_cfpa_NFI = filter(donors, donors$distribution_information.distribution_donor == "cfpa")%>%
  group_by(distribution_information.vdc_name) %>% 
  summarize(PlannedNFI_CFPA = sum(distribution_information.number_of_kits, na.rm = TRUE))

distributions_cfpa_cash = filter(donors, donors$distribution_information.distribution_donor == "cfpa") %>%
  group_by(distribution_information.vdc_name) %>% 
  summarize(PlannedCash_CFPA = sum(distribution_information.cash_recipients, na.rm = TRUE))

distributions_ofda_NFI = filter(donors, donors$distribution_information.distribution_donor == "ofda")%>%
  group_by(distribution_information.vdc_name) %>% 
  summarize(PlannedNFI_OFDA = sum(distribution_information.number_of_kits, na.rm = TRUE))

distributions_ofda_cash = filter(donors, donors$distribution_information.distribution_donor == "ofda") %>%
  group_by(distribution_information.vdc_name) %>% 
  summarize(PlannedCash_OFDA = sum(distribution_information.cash_recipients, na.rm = TRUE))

distributions_private_NFI = filter(donors, donors$distribution_information.distribution_donor == "private")%>%
  group_by(distribution_information.vdc_name) %>% 
  summarize(PlannedNFI_Private = sum(distribution_information.number_of_kits, na.rm = TRUE))

distributions_private_cash = filter(donors, donors$distribution_information.distribution_donor == "private") %>%
  group_by(distribution_information.vdc_name) %>% 
  summarize(PlannedCash_Private = sum(distribution_information.cash_recipients, na.rm = TRUE))

donor_vdc_summary = Reduce(function(...) merge(...,by="distribution_information.vdc_name" ,all=T), list(distributions_private_cash, distributions_private_NFI, distributions_ofda_cash, distributions_ofda_NFI, distributions_cfpa_cash,distributions_cfpa_NFI,distributions_dfid_cash, distributions_dfid_NFI))

donor_vdc_summary$NFI_sum = rowSums(donor_vdc_summary[, c(2,4,6,8)], na.rm = TRUE )

#donor_vdc_summary = merge(donor_vdc_summary, previous_distributions, by.x = "distribution_information.vdc_name", by.y = "VDC", all = TRUE)

```

Report Generated on `r date()`. 

